# Generated by Django 2.0.6 on 2018-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180619_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
