# Generated by Django 2.0.6 on 2018-06-19 09:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
    ]
