# Generated by Django 2.0.6 on 2018-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180619_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='block_users',
            field=models.ManyToManyField(blank=True, related_name='block_friends', to='members.BlogUser'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='members.BlogUser'),
        ),
    ]
