# Generated by Django 2.0.6 on 2018-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180619_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='block_users',
            field=models.ManyToManyField(related_name='block_friends', to='members.BlogUser'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='members.BlogUser'),
        ),
    ]
